### PR TITLE
ISSUE 220: ensure apt-key gpg in install.sh

### PR DESCRIPTION
**Pull request by mroder-emnify**
Adresses: https://github.com/mondoohq/client/issues/220

Use apt keyring with `apt-key add` instead of `gpg --dearmor`

### CODE REVIEW

**Comment by mroder-emnify** [comment]
recheck

**Comment by chris-rock** [comment]
Super great addition @mroder-emnify

We need to add shellcheck to the github actions. Right now it prints two warnings:

```
 make test/shellcheck                                                                                                                                                                                                                                                              x2 1h27m patch-1[4210239]
shellcheck install.sh

In install.sh line 341:
      APT_VERSION=`dpkg-query --show --showformat '${Version}' apt`
                  ^-- SC2006 (style): Use $(...) notation instead of legacy backticks `...`.

Did you mean: 
      APT_VERSION=$(dpkg-query --show --showformat '${Version}' apt)


In install.sh line 342:
      if dpkg --compare-versions ${APT_VERSION} le 1.0.2;
                                 ^------------^ SC2086 (info): Double quote to prevent globbing and word splitting.

Did you mean: 
      if dpkg --compare-versions "${APT_VERSION}" le 1.0.2;
```

Do you want to handle that? Otherwise we can do that as a followup PR.

**Comment by mroder-emnify** [comment]
I will handle that...

**Review by chris-rock — APPROVED** [review]
💯 Thank you for the great improvement @mroder-emnify

**Pull request merged**
