### PR TITLE
One-line change to align install scripts

### PR DESCRIPTION
**Pull request by charlesjohnson**
This one-liner aligns the install.sh script in this repo with the version in the mondoo repo

Signed-off-by: Charles Johnson <chip@mondoo.com>

### CODE REVIEW

**Review by benr — APPROVED** [review]

**Comment by charlesjohnson** [comment]
Screenshot 2022-11-17 at 6 55 06 PM
Screenshot 2022-11-17 at 6 55 16 PM

**Comment by charlesjohnson** [comment]
Screenshot 2022-11-17 at 6 57 32 PM
Screenshot 2022-11-17 at 6 57 51 PM

**Comment by charlesjohnson** [comment]
Screenshot 2022-11-17 at 6 58 27 PM
Screenshot 2022-11-17 at 6 58 44 PM

**Comment by charlesjohnson** [comment]
You can check these yourself by firing up the site with yarn dev, exporting with ngrok, and then feeding it through https://opengraph.xyz. The last step is to hand-edit the image URL in the left box after the page loads.

**Pull request merged**
